### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by hipstersmoothie** [Borewit/tokenizer-token#1]
Seem like the license text is not included with this project. This caused my license automation to fail
![Screen Shot 2020-01-13 at 9 28 40 AM](https://user-images.githubusercontent.com/1192452/72277636-1ab4de80-35e7-11ea-81f5-19ffa3f8f2a6.png)

**Comment by Borewit** [comment]
Thanks for letting me know. I think that is already fixed via 098009df4fb2ca92c209509735a3c23a6d734564 in [v0.1.1](https://github.com/Borewit/tokenizer-token/releases/tag/v0.1.1)

**Comment by v-anyukov** [comment]
Hello, is it possible to add license text itself (not only mention in package.json) here on gihub?
Thanks in advance

**Comment by Borewit** [comment]
Is this sufficient: 89c3fd99c604bb85b2a8048a78842bd432744017 @v-anyukov?

**Comment by v-anyukov** [comment]
@Borewit Yup, thanks a lot.
